import client from "common/services/BEService";

class CandidatoServiceC{

    search =  (
        pageNum: number,
        pageSize: number,
        filtering:any,
        sorting: any,
        include?: boolean
      ) => {
        
          const params = {
            pageNum,
            pageSize,
            include,
          };
    
          return Promise.resolve({
            data: [
        {
            "IDCANDIDATO": 22,
            "first_name": "NAVYASREE",
            "last_name": "MYAKALA",
            "IDTIPOSENIORITY": null,
            "DESCRIZIONETIPOSENIORITY": null,
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": null,
            "SKILLS": "2",
            "skills": "Java",
            "ANNONASCITA": null,
            "IDLOGAZIONECANDIDATO": 55,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-13T10:05:55.927",
            "IDTIPOCONTRATTOLAVORO": null,
            "CODICETIPOCONTRATTOLAVORO": null,
            "DESCRIZIONETIPOCONTRATTOLAVORO": null,
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Milano",
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 23,
            "first_name": "Marco",
            "last_name": "Bertolasi",
            "IDTIPOSENIORITY": 3,
            "DESCRIZIONETIPOSENIORITY": "Senior",
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Functional Analyst",
            "SKILLS": "165,183",
            "skills": "ASP.NET,C#",
            "ANNONASCITA": 1985,
            "IDLOGAZIONECANDIDATO": 109,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:22:30.047",
            "IDTIPOCONTRATTOLAVORO": 2,
            "CODICETIPOCONTRATTOLAVORO": "IND",
            "DESCRIZIONETIPOCONTRATTOLAVORO": "Tempo Inderminato",
            "FLAGBLACKLIST": 0,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Milano",
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 26,
            "first_name": "Diego ",
            "last_name": "Falcone",
            "IDTIPOSENIORITY": null,
            "DESCRIZIONETIPOSENIORITY": null,
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Analista funzionale/PMO",
            "SKILLS": "141,6,3,10,74",
            "skills": "C++,JavaScript,HTML,SQL,Agile",
            "ANNONASCITA": 1972,
            "IDLOGAZIONECANDIDATO": 110,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:22:38.213",
            "IDTIPOCONTRATTOLAVORO": null,
            "CODICETIPOCONTRATTOLAVORO": null,
            "DESCRIZIONETIPOCONTRATTOLAVORO": null,
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Milano",
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 27,
            "first_name": "ANDREA",
            "last_name": "Mazzucchelli",
            "IDTIPOSENIORITY": null,
            "DESCRIZIONETIPOSENIORITY": null,
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Analista funzionale ",
            "SKILLS": "3,7,6,2,10",
            "skills": "HTML,CSS,JavaScript,Java,SQL",
            "ANNONASCITA": 1994,
            "IDLOGAZIONECANDIDATO": 111,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:22:53.367",
            "IDTIPOCONTRATTOLAVORO": null,
            "CODICETIPOCONTRATTOLAVORO": null,
            "DESCRIZIONETIPOCONTRATTOLAVORO": null,
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": null,
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 28,
            "first_name": "Rebecca Maria ",
            "last_name": "Di Donato ",
            "IDTIPOSENIORITY": null,
            "DESCRIZIONETIPOSENIORITY": null,
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Analista Funzionale ",
            "SKILLS": "2,10",
            "skills": "Java,SQL",
            "ANNONASCITA": 1995,
            "IDLOGAZIONECANDIDATO": 112,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:23:20.123",
            "IDTIPOCONTRATTOLAVORO": null,
            "CODICETIPOCONTRATTOLAVORO": null,
            "DESCRIZIONETIPOCONTRATTOLAVORO": null,
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": null,
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 29,
            "first_name": "Michele ",
            "last_name": "Pagani ",
            "IDTIPOSENIORITY": null,
            "DESCRIZIONETIPOSENIORITY": null,
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": null,
            "SKILLS": "2,42,43",
            "skills": "Java,Struts,Hibernate",
            "ANNONASCITA": 1976,
            "IDLOGAZIONECANDIDATO": 64,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-13T14:58:20.757",
            "IDTIPOCONTRATTOLAVORO": null,
            "CODICETIPOCONTRATTOLAVORO": null,
            "DESCRIZIONETIPOCONTRATTOLAVORO": null,
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Milano",
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 30,
            "first_name": "Stefano ",
            "last_name": "Migale ",
            "IDTIPOSENIORITY": 2,
            "DESCRIZIONETIPOSENIORITY": "Middle",
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Analista Funzionale ",
            "SKILLS": "10,187",
            "skills": "SQL,Excel",
            "ANNONASCITA": 1995,
            "IDLOGAZIONECANDIDATO": 113,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:23:25.5",
            "IDTIPOCONTRATTOLAVORO": 2,
            "CODICETIPOCONTRATTOLAVORO": "IND",
            "DESCRIZIONETIPOCONTRATTOLAVORO": "Tempo Inderminato",
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Milano",
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 41,
            "first_name": "Mauro ",
            "last_name": "Carlucci ",
            "IDTIPOSENIORITY": 2,
            "DESCRIZIONETIPOSENIORITY": "Middle",
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Data Analyst",
            "SKILLS": "12",
            "skills": "PL\\SQL",
            "ANNONASCITA": 1987,
            "IDLOGAZIONECANDIDATO": 114,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:23:29.803",
            "IDTIPOCONTRATTOLAVORO": 2,
            "CODICETIPOCONTRATTOLAVORO": "IND",
            "DESCRIZIONETIPOCONTRATTOLAVORO": "Tempo Inderminato",
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Milano",
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 42,
            "first_name": "Carlotta ",
            "last_name": "Schwarz",
            "IDTIPOSENIORITY": null,
            "DESCRIZIONETIPOSENIORITY": null,
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Functional Analyst",
            "SKILLS": "10,187",
            "skills": "SQL,Excel",
            "ANNONASCITA": 1994,
            "IDLOGAZIONECANDIDATO": 90,
            "CODICETIPOAZIONERECRUITER": "CON",
            "DESCTIPOAZIONERECRUITER": "Contatto",
            "date_updated": "2022-01-14T12:27:53.097",
            "IDTIPOCONTRATTOLAVORO": null,
            "CODICETIPOCONTRATTOLAVORO": null,
            "DESCRIZIONETIPOCONTRATTOLAVORO": null,
            "FLAGBLACKLIST": null,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": null,
            "FLGATTIVO": 1
        },
        {
            "IDCANDIDATO": 43,
            "first_name": "Emanuela ",
            "last_name": "Del Vescovo",
            "IDTIPOSENIORITY": 3,
            "DESCRIZIONETIPOSENIORITY": "Senior",
            "IDTIPOPROFILOLAVORATIVO": 4,
            "CODICETIPOPROFILOLAVORATIVO": "AN",
            "job_profile": "Analista",
            "TIPOLOGIAPROFILO": "Functional Analyst",
            "SKILLS": "10,12,139",
            "skills": "SQL,PL\\SQL,Cobol",
            "ANNONASCITA": 1972,
            "IDLOGAZIONECANDIDATO": 115,
            "CODICETIPOAZIONERECRUITER": "R",
            "DESCTIPOAZIONERECRUITER": "Rimozione",
            "date_updated": "2022-01-14T16:23:37.05",
            "IDTIPOCONTRATTOLAVORO": 2,
            "CODICETIPOCONTRATTOLAVORO": "IND",
            "DESCRIZIONETIPOCONTRATTOLAVORO": "Tempo Inderminato",
            "FLAGBLACKLIST": 0,
            "FLAGDISPONIBILETRANSFER": 0,
            "SEDIVALUTATE": "Roma",
            "FLGATTIVO": 1
        }
                        ],
            meta: {
                total:10
                }
        })

          return client.post(
            `api/v1/candidates`,
            { filtering, sorting },
            { params }
          ).then(res=>res.data)
          
        
      };
}

export const candidatoService = new CandidatoServiceC();