// formFields.ts
import { AnagraficaData, TrattamentoEconomicoData, RuoliData } from './modelForms';

export const getFormAnagraficaFields = (formData: AnagraficaData) => ({
    sede: {
        name: "sede",
        label: "Sede",
        type: "select",
        value: formData.sede || "",
        required: true,
        options: ["Barletta", "Milano", "Roma"],
        validator: (value: any) => value ? "" : "Il campo sede è obbligatorio",
    },
    nome: {
        name: "nome",
        label: "Nome",
        type: "text",
        value: formData.nome || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Nome è obbligatorio",
    },
    cognome: {
        name: "cognome",
        label: "Cognome",
        type: "text",
        value: formData.cognome || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Cognome è obbligatorio",
    },
    email: {
        name: "email",
        label: "Email Aziendale",
        type: "email",
        value: formData.email || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Email Aziendale è obbligatorio",
    },
    matricola: {
        name: "matricola",
        label: "Matricola",
        type: "text",
        value: formData.matricola || "",
    },
    sesso: {
        name: "sesso",
        label: "Sesso",
        type: "select",
        value: formData.sesso || "",
        options: ["Femmina", "Maschio"],
    },
    Provincianascita: {
        name: "Provincianascita",
        label: "Provincia di Nascita",
        type: "text",
        value: formData.Provincianascita || "",
    },
    comuneNascita: {
        name: "comuneNascita",
        label: "Comune di Nascita",
        type: "text",
        value: formData.comuneNascita || "",
    },
    residenza: {
        name: "residenza",
        label: "Provincia di Residenza",
        type: "text",
        value: formData.residenza || "",
    },
    comuneResidenza: {
        name: "comuneResidenza",
        label: "Comune di Residenza",
        type: "text",
        value: formData.comuneResidenza || "",
    },
    indirizzoResidenza: {
        name: "indirizzoResidenza",
        label: "Indirizzo di Residenza",
        type: "text",
        value: formData.indirizzoResidenza || "",
    },
    dataNascita: {
        name: "dataNascita",
        label: "Data di Nascita",
        type: "date",
        value: formData.dataNascita || "",
    },
    cap: {
        name: "cap",
        label: "CAP di Residenza",
        type: "number",
        value: formData.cap || 0,
    },
    cellulare: {
        name: "cellulare",
        label: "Cellulare",
        type: "number",
        value: formData.cellulare || 0,
    },
    telefonoCasa: {
        name: "telefonoCasa",
        label: "Telefono di Casa",
        type: "number",
        value: formData.telefonoCasa || 0,
    },
    telefonoLavoro: {
        name: "telefonoLavoro",
        label: "Telefono di Lavoro",
        type: "number",
        value: formData.telefonoLavoro || 0,
    },
    emailPrivata: {
        name: "emailPrivata",
        label: "Email Privata",
        type: "email",
        value: formData.emailPrivata || "",
    },
    iban: {
        name: "iban",
        label: "IBAN",
        type: "text",
        value: formData.iban || "",
    },
    codiceFiscale: {
        name: "codiceFiscale",
        label: "Codice Fiscale",
        type: "text",
        value: formData.codiceFiscale || "",
    },
});

export const getFormTrattamentoEconomicoFields = (formData: TrattamentoEconomicoData) => ({
    tipologiaContratto: {
        name: "tipologiaContratto",
        label: "Tipologia di Contratto di Lavoro",
        type: "text",
        value: formData.tipologiaContratto || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Tipologia Contratto è obbligatorio",
    },
    societa: {
        name: "societa",
        label: "Società",
        type: "text",
        value: formData.societa || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo società è obbligatorio",
    },
    tipoAmbitoLavorativo: {
        name: "tipoAmbitoLavorativo",
        label: "Tipo Ambito Lavorativo",
        type: "text",
        value: formData.tipoAmbitoLavorativo || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Tipo Ambito Lavorativo è obbligatorio",
    },
    dataInizioTrattamento: {
        name: "dataInizioTrattamento",
        label: "Data di Inizio del Trattamento",
        type: "date",
        value: formData.dataInizioTrattamento || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Data Inizio del Trattamento è obbligatorio",
    },
    costoGiornaliero: {
        name: "costoGiornaliero",
        label: "Costo Giornaliero",
        type: "number",
        value: formData.costoGiornaliero || 0,
        required: true,
        validator: (value: any) => value ? "" : "Il campo Costo Giornaliero è obbligatorio",
    },
    dataAssunzione: {
        name: "dataAssunzione",
        label: "Data Assunzione",
        type: "date",
        value: formData.dataAssunzione || "",
    },
    scadenzaEffettiva: {
        name: "scadenzaEffettiva",
        label: "Scadenza Effettiva",
        type: "date",
        value: formData.scadenzaEffettiva || "",
    },
    dataRecesso: {
        name: "dataRecesso",
        label: "Data del Recesso",
        type: "date",
        value: formData.dataRecesso || "",
    },
    motivazioneCessazione: {
        name: "motivazioneCessazione",
        label: "Motivazione della Cessazione",
        type: "textarea",
        value: formData.motivazioneCessazione || "",
    },
    trasformazioni: {
        name: "trasformazioni",
        label: "Trasformazioni",
        type: "textarea",
        value: formData.trasformazioni || "",
    },
    ccnl: {
        name: "ccnl",
        label: "CCNL",
        type: "text",
        value: formData.ccnl || "",
    },
    ral: {
        name: "ral",
        label: "RAL",
        type: "number",
        value: formData.ral || 0,
    },
    trasferta: {
        name: "trasferta",
        label: "Trasferta",
        type: "number",
        value: formData.trasferta || 0,
    },
    buoniPasto: {
        name: "buoniPasto",
        label: "Buoni Pasto",
        type: "number",
        value: formData.buoniPasto || 0,
    },
    nettoMese: {
        name: "nettoMese",
        label: "Netto del mese",
        type: "number",
        value: formData.nettoMese || 0,
    },
    costoAnnuale: {
        name: "costoAnnuale",
        label: "Costo Annuo",
        type: "number",
        value: formData.costoAnnuale || 0,
    },
    tariffaVendita: {
        name: "tariffaVendita",
        label: "Tariffa di Vendita",
        type: "number",
        value: formData.tariffaVendita || 0,
    },
    note: {
        name: "note",
        label: "Note",
        type: "textarea",
        value: formData.note || "",
    },
});

export const getFormRuoliFields = (formData: RuoliData) => ({
    ruolo: {
        name: "ruolo",
        label: "Ruolo",
        type: "text",
        value: formData.ruolo || "",
        required: true,
        validator: (value: any) => value ? "" : "Il campo Ruolo è obbligatorio",
    },
    // ... other fields for ruoli
});
