declare module "common/Theme";
declare module "common/DrawerService";
declare module "common/Tab";
declare module "common/Form"
declare module "common/Table"
declare module "common/Modal"
declare module "common/services/BEService";
declare module "common/Calendar";
declare module "common/InlineEditTable";
declare module "common/Window";
declare module "common/Button";
declare module "common/CustomListView";
declare module "common/providers/NotificationProvider"
